language: node_js
node_js:
  - "lts/*"
  - "node"

cache:
  directories:
    - ~/.npm

notifications:
  email: false

script:
  - npm run doc
  - npm run flow
  - npm run lint
  - npm run examples
  - npm run codecov

before_deploy:
  - rm -rf deploy
  - mkdir -p deploy
  - cp -r doc deploy/bitconchWeb3Api-$TRAVIS_BRANCH
  - cp lib/index.iife.js deploy/bitconchWeb3.min.js
  - ( cd deploy; tar zcf bitconchWeb3Api.tgz bitconchWeb3Api-$TRAVIS_BRANCH )

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: doc
    on:
      branch: master
      node_js: "lts/*"
  - provider: script
    skip_cleanup: true
    script:
      - npx semantic-release
    on:
      branch: master
      node_js: "lts/*"
  - provider: releases
    skip-cleanup: true
    file:
      - deploy/bitconchWeb3.min.js
      - deploy/bitconchWeb3Api.tgz
    api_key: $GITHUB_TOKEN
    on:
      tags: true
      node_js: "lts/*"
